"""init_db

迁移 ID: 5dc8350e81c9
父迁移:
创建时间: 2023-11-15 13:32:06.312216

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5dc8350e81c9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("blive",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blive_biliuserrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("room_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blive_biliuserrecord")),
    )
    op.create_table(
        "blive_subscriptionrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target", sa.JSON(), nullable=False),
        sa.Column("live", sa.Boolean(), nullable=False),
        sa.Column("dynamic", sa.Boolean(), nullable=False),
        sa.Column("record", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blive_subscriptionrecord")),
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blive_subscriptionrecord")
    op.drop_table("blive_biliuserrecord")
    # ### end Alembic commands ###
