"""init

Revision ID: e70d4af70c29
Revises: 
Create Date: 2023-07-21 19:57:58.076204

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e70d4af70c29"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blive_biliuserrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("room_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "blive_subscriptionrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target", sa.JSON(), nullable=False),
        sa.Column("live", sa.Boolean(), nullable=False),
        sa.Column("dynamic", sa.Boolean(), nullable=False),
        sa.Column("record", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["blive_biliuserrecord.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blive_subscriptionrecord")
    op.drop_table("blive_biliuserrecord")
    # ### end Alembic commands ###
