"""uid_type

迁移 ID: ec5ca33e1d32
父迁移: 5dc8350e81c9
创建时间: 2024-03-04 00:01:09.713257

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ec5ca33e1d32"
down_revision: str | Sequence[str] | None = "5dc8350e81c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blive_biliuserrecord", schema=None) as batch_op:
        batch_op.alter_column(
            "uid",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.Integer(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "room_id",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.Integer(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blive_biliuserrecord", schema=None) as batch_op:
        batch_op.alter_column(
            "room_id",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=64),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "uid",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
