"""init_db

迁移 ID: 8a0475a45450
父迁移:
创建时间: 2024-07-13 11:49:38.000398

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8a0475a45450"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("mczju",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mczju_messagerecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column("message", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mczju_messagerecord")),
        info={"bind_key": "mczju"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mczju_messagerecord")
    # ### end Alembic commands ###
